// noinspection SpellCheckingInspection: a lot of weird language words

/**
 * This file contains metadata about the registered languages.
 *
 * It is generated by `gen_lang.mjs`. Do not edit this file manually unless you really know what you are doing.
 *
 * The metadata gets pulled from [`@sozialhelden/ietf-language-tags`](https://npm.im/@sozialhelden/ietf-language-tags)
 * by the script.
 */
export default {};

export interface IRegistryEntry {
    Type: string;
    Tag?: string;
    Subtag: string;
    Description?: string[];
    Scope?: string;
    Added: string;
    Deprecated?: string;
    "Preferred-Value"?: string;
    Prefix?: string[];
    Comments?: string[];
    Macrolanguage?: string;
    "Suppress-Script"?: string;
}

export interface ILanguageSubtag {
    langtag: string;
    language?: string;
    extlang?: string;
    script?: string;
    region?: string;
    variants?: string[];
    extensions?: Record<string, string>;
    privateuse?: string;
    grandfathered?: string;
}

export interface ILanguageTag {
    langtag?: IRegistryEntry;
    language?: IRegistryEntry;
    extlang?: IRegistryEntry;
    script?: IRegistryEntry;
    region?: IRegistryEntry;
    variants?: IRegistryEntry[];
    extensions?: Record<string, IRegistryEntry>;
    privateuse?: IRegistryEntry;
    grandfathered?: IRegistryEntry;
    redundant?: IRegistryEntry;
    variant?: IRegistryEntry;
    collection?: IRegistryEntry;
    macrolanguage?: IRegistryEntry;
    special?: IRegistryEntry;
    parts: ILanguageSubtag;
}

/**
 * Language metadata for all registered languages.
 *
 * If this seems outdated, run `node gen_lang.mjs` in this directory.
 */
export let languageMetadata: Array<ILanguageTag> = /*__FLAG_START__*/[{
    "parts": {
        "langtag": "de-DE",
        "language": "de",
        "region": "DE",
    },
    "language": {
        "Type": "language",
        "Subtag": "de",
        "Description": ["German"],
        "Added": "2005-10-16",
        "Suppress-Script": "Latn",
    },
    "region": {"Type": "region", "Subtag": "DE", "Description": ["Germany"], "Added": "2005-10-16"},
}, {
    "parts": {"langtag": "en-US", "language": "en", "region": "US"},
    "language": {
        "Type": "language",
        "Subtag": "en",
        "Description": ["English"],
        "Added": "2005-10-16",
        "Suppress-Script": "Latn",
    },
    "region": {"Type": "region", "Subtag": "US", "Description": ["United States"], "Added": "2005-10-16"},
}]/*__FLAG_END__*/;
